# TECHNOVA INFRASTRUCTURE V3.0 - DOCKER READY & CI/CD RESILIENT
services:
  db:
    container_name: technova_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: technovapass
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      # FIX: Aumentamos a paciência do Docker para servidores lentos do GitHub Actions
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - technova-network

  backend:
    container_name: technova_backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=technovapass
      - DB_NAME=admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - technova-network

  frontend:
    container_name: technova_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - technova-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: technova_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - technova-network

  grafana:
    image: grafana/grafana:latest
    container_name: technova_grafana
    ports:
      - "3001:3000" # Mapeado para 3001 para não conflitar com seu frontend no 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - technova-network
    volumes:
      - grafana-storage:/var/lib/grafana  

networks:
  technova-network:
    driver: bridge

volumes:
  grafana-storage: