name: TechNova CI - Quality Gate

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  cypress-run:
    name: 🧪 Build and Test (Headless)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: technovapass
          # Ajustado para 'admin' para evitar o erro "database does not exist"
          POSTGRES_DB: admin 
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js (V22)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Install Root Dependencies
        run: npm ci

      - name: 🛠️ Install Backend Dependencies
        run: cd backend && npm install

      - name: ⚙️ Run TechNova Setup
        run: npm run setup

      # PASSO VITAL: Criar as tabelas na CI antes dos testes
      - name: 🗄️ Seed Database
        run: |
          PGPASSWORD=technovapass psql -h localhost -U admin -d admin -f backend/init.sql

      - name: 🏁 Cypress Run (E2E)
        uses: cypress-io/github-action@v6
        with:
          start: npm run backend, npm run frontend
          wait-on: 'http://localhost:5000/api/v1/products, http://localhost:3000'
          wait-on-timeout: 150
          browser: chrome