name: TechNova CI - Quality Gate

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  cypress-run:
    name: 🧪 Build and Test (Headless)
    runs-on: ubuntu-latest
    
    # O GitHub providencia o Postgres nativo aqui
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: technovapass
          POSTGRES_DB: technova_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js (V22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm install

      - name: ⚙️ Setup TechNova Environment
        # Cria os ficheiros .env virtuais no runner
        run: npm run setup

      - name: 🧪 Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          # O SEGREDO: Vírgula separa múltiplos comandos e evita erro de "path argument"
          start: npm run backend, npm run frontend
          # Aguarda a API e o Frontend estarem online para começar
          wait-on: 'http://localhost:5000/api/v1/products, http://localhost:3000'
          wait-on-timeout: 120
          # Executa todos os specs, incluindo o de sanidade
          spec: cypress/e2e/**/*.cy.js

      - name: 📸 Upload Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: 🎥 Upload Test Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos