name: TechNova CI/CD (Docker Ready)

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  e2e-testing:
    # Usaremos o Ubuntu que é o padrão ouro para rodar Docker no GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do Repositório
        uses: actions/checkout@v4

      - name: 🔐 Criar arquivo .env para o Docker
        run: |
          echo "DB_HOST=db" > .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=admin" >> .env
          echo "DB_PASSWORD=technovapass" >> .env
          echo "DB_NAME=admin" >> .env

      - name: 🐳 Subir Infraestrutura Full Stack (Docker Compose)
        run: docker compose up -d --build

      - name: 📦 Instalar dependências locais (Cypress)
        run: npm install

      - name: 🧪 Executar Testes E2E (Cypress)
        uses: cypress-io/github-action@v6
        with:
          # O Cypress vai aguardar o Frontend e a API estarem 100% online antes de testar
          wait-on: 'http://localhost:3000, http://localhost:5000/api/v1/wallet'
          wait-on-timeout: 120